version: "3"
services:
  api:
    container_name: api
    image: api
    build:
      context: .
      target: development
      args:
        - APP=api
    command: pnpm run start:dev api
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - user
    networks:
      - gmg-network
  auth:
    container_name: auth
    image: auth
    build:
      context: .
      target: development
      args:
        - APP=auth
    command: pnpm run start:dev auth
    ports:
      - '3001:3001/tcp'
    networks:
      - gmg-network

  user:
    container_name: user
    image: user
    build:
      context: .
      target: development
      args:
        - APP=user
    command: pnpm run start:dev user
    ports:
      - '3002:3002/tcp'
    networks:
      - gmg-network

networks:
  gmg-network:
    driver: bridge
